name: docker-build-push

on:
  workflow_call:
    inputs:
    docker-repository-name:
        required: true
        type: string
    docker-tag:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and tag Docker image
        run: |
          docker build -t dghogare/hello-world:latest .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker-repository-name }}:${{ inputs.docker-tag }}
      
      