name: java-gradle-ci

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      gradle-version:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ inputs.gradle-version }}
      - name: Check gradle version
        run: gradle --version
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Copy Jar file
        run: mv build/libs/$(ls build/libs) app.jar
      - uses: actions/upload-artifact@master
        with:
          name: jar-file
          path: app.jar