# .github/workflows/main.yaml
name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/java-gradle-ci.yaml
    with:
      java-version: '17' # Provide java version
      gradle-version: '8.5' # Provide Gradle version


    