# .github/workflows/main.yaml
name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/java-gradle-ci.yml
    with:
      java-version: '17' # Provide java version
      gradle-version: '8.5' # Provide Gradle version
    uses: ./.github/workflows/sonar-scan.yml
    uses: ./.github/workflows/docker-build.yml
    with:
      docker-repository-name: 'hello-world' #"Provide application name to push docker image"
      docker-tag: 'v1'  # Docker Tag to define applicaiotn versions.


    