# .github/workflows/main.yaml
name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/java-gradle-ci.yaml
    with:
      java-version: '17' # Provide java version
      gradle-version: '8.5' # Provide Gradle version
  call-reusable-workflow:
    uses: ./.github/workflows/java-gradle-ci.yaml
    with:
      docker-repository-name: '17' # Provide applicaiton name for repository
      docker-tag: 'v1' # Provide Gradle version
  

    